/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ANNDaemon_constants.h"

namespace gvlad {

const ANNDaemonConstants g_ANNDaemon_constants;

ANNDaemonConstants::ANNDaemonConstants() {
}

} // namespace

