/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ANNDaemon_CONSTANTS_H
#define ANNDaemon_CONSTANTS_H

#include "ANNDaemon_types.h"

namespace gvlad {

class ANNDaemonConstants {
 public:
  ANNDaemonConstants();

};

extern const ANNDaemonConstants g_ANNDaemon_constants;

} // namespace

#endif
