/*
 * compute_gvlad.cpp
 *
 *  Created on: Jun 24, 2013
 *      Author: daniewang
 */

#include <boost/bind.hpp>
#include <boost/lambda/lambda.hpp>
#include "gvlad/lib/File.h"
#include "gvlad/lib/Serializer.h"
#include "gvlad/lib/Vocabulary.h"

std::string descriptor_dir;
std::string vocabulary;
std::string adaptation;
std::string geo_dir;
std::vector<std::string> file_vector;

void compute_feature(size_t i) {
	std::string stem = File::get_stem(file_vector[i]);
	GeoDescriptorVector<float> geo_descriptor_vector;
	geo_descriptor_vector.load(file_vector[i]);
	std::vector<float> feature;
	Vocabulary::instance()->compute_gvlad(feature,
			geo_descriptor_vector);
	Serializer::save(feature, geo_dir + "/" + stem + ".feature");
	std::cout << "computing gvlad for " << file_vector[i] << "..." << std::endl;
}

int main(int argc, char* argv[]) {
	if (argc == 1) {
		std::cout
				<< "Usage: ./compute_gvlad descriptor_dir vocabulary adaptation feature_dir"
				<< std::endl;
		std::cout << "descriptor_dir is the directory of the image descriptors." << std::endl;
		std::cout << "vocabulary is the vocabulary xml file generated by compute_vocabulary." << std::endl;
		std::cout << "adaptation is the adaptation xml file generated by compute_adaptation." << std::endl;
		std::cout << "feature_dir is the output directory of geometric vlad features." << std::endl;
		std::cout << "For example: ./compute_gvlad ~/surf ~/vocabulary.xml ~/adaptation.xml ~/gvlad" << std::endl;
		return 0;
	}
	if (argc == 5) {
		descriptor_dir = argv[1];
		vocabulary = argv[2];
		adaptation = argv[3];
		geo_dir = argv[4];
		boost::filesystem::create_directories(geo_dir);
		Vocabulary::instance()->load(vocabulary);
		Vocabulary::instance()->load_adaptation(adaptation);
		File::get_files(file_vector, descriptor_dir);
		for (size_t i = 0; i < file_vector.size(); ++i) {
			compute_feature(i);
		}
	}
	return 0;
}

